#!/bin/bash

WORK_DIR=$PWD
SCRIPTS_DIR=$WORK_DIR/scripts

file=$1
filename="${file##*/}"
article_name="${filename%.*}"

sentence_dir=$SCRIPTS_DIR/paragraphs/$article_name
passage_dir=$SCRIPTS_DIR/passages/$article_name


echo "+--------------------- Project Launch ----------------------+"
echo "|      © Text Simplification/Internship Work - 2018         |"
echo "+--------------------------------------------------------- -+"


# Test if text file (to change)
if ! [ "$#" -eq 1 ] || ! [ -f "$1" ] || ! [[ $1 == *.txt ]]; then
  echo " Please give a text file as unique argument "
  exit 1
fi


# Setup diretory for the generated split paragraphs from text

if [ -e $sentence_dir ]; then
    rm -f $sentence_dir/*.txt
else
    mkdir -p $SCRIPTS_DIR/paragraphs/
    mkdir $sentence_dir/
fi

if [ -e $passage_dir ]; then
    rm -f $passage_dir/*.txt
else
    mkdir -p $SCRIPTS_DIR/passages/
    mkdir $passage_dir/
fi


# Spliting text to paragraphs
python $SCRIPTS_DIR/text_to_paragraphs.py $WORK_DIR/$1
echo "---------------------- Text splited to paragraphs DONE"


# Parse the paragraphs
python -m tupa $sentence_dir/*.txt -m $WORK_DIR/TUPA_models/ucca-bilstm
mv *.xml $passage_dir
echo "---------------------- Parsed DONE"


# util now the first argument should be an XML file to split
# copy the spliting sentence into a text file
python $SCRIPTS_DIR/_1_Split_sentence.py $passage_dir > $sentence_dir/Splitting.txt
cat $sentence_dir/Splitting.txt > $WORK_DIR/NeuralTextSimplification_model/data/test.en
#cat $sentence_dir/Splitting.txt > $WORK_DIR/NeuralTextSimplification_model/data/test.sen
echo "---------------------- Splitting DONE"

# Pass sentences through the Neural Component
cd $WORK_DIR/NeuralTextSimplification_model/src/scripts/
source $WORK_DIR/NeuralTextSimplification_model/src/scripts/translate.sh
cd ../../results_NTS
echo "---------------------- Gone through the Neural Network"

value=$(<result_NTS_epoch11_10.19.t7_5)
echo "$value"

# evaluate the script
python $WORK_DIR/NeuralTextSimplification_model/src/evaluate.py $WORK_DIR/NeuralTextSimplification_model/data/test.en $WORK_DIR/NeuralTextSimplification_model/data/references/references.tsv $WORK_DIR/NeuralTextSimplification_model/predictions/

cd $WORK_DIR
echo "$value" >> $article_name-simple.txt

read -p "Delete generated xml files? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    rm $passage_dir/* # remove all XML files
fi
